/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samuel.escuela.form;

import com.samuel.escuela.component.DesckTopPaneBackGround;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author cobrakik01
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnAlumnos = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jifAlumnos = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpAlumnos = new javax.swing.JPanel();
        alumnoMasterDetailForm1 = new com.samuel.escuela.form.AlumnoMasterDetailForm();
        jifMaterias = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        materiaMasterDetailForm1 = new com.samuel.escuela.form.MateriaMasterDetailForm();
        jifProfesores = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        profesorMasterDetailForm1 = new com.samuel.escuela.form.ProfesorMasterDetailForm();
        jifGrupos = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        grupoMasterDetailForm1 = new com.samuel.escuela.form.GrupoMasterDetailForm();
        jifUsuarios = new javax.swing.JInternalFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        usuarioMasterDetailForm1 = new com.samuel.escuela.form.UsuarioMasterDetailForm();
        jifAsignarMaterias = new javax.swing.JInternalFrame();
        jScrollPane8 = new javax.swing.JScrollPane();
        jpAsignarMaterias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(new DesckTopPaneBackGround(new ImageIcon(this.getClass().getResource("/com/samuel/escuela/icon/tollbar.png"))));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/samuel/escuela/icon/student_24px.png"))); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setFocusable(false);
        btnAlumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlumnos.setOpaque(false);
        btnAlumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlumnos);

        btnMaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/samuel/escuela/icon/materia_24px.png"))); // NOI18N
        btnMaterias.setText("Materias");
        btnMaterias.setFocusable(false);
        btnMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaterias.setOpaque(false);
        btnMaterias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMaterias);

        btnProfesores.setForeground(new java.awt.Color(255, 255, 255));
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/samuel/escuela/icon/profesores_24px.png"))); // NOI18N
        btnProfesores.setText("Profesores");
        btnProfesores.setFocusable(false);
        btnProfesores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfesores.setOpaque(false);
        btnProfesores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProfesores);

        btnGrupos.setForeground(new java.awt.Color(255, 255, 255));
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/samuel/escuela/icon/grupo_24px.png"))); // NOI18N
        btnGrupos.setText("Grupos");
        btnGrupos.setFocusable(false);
        btnGrupos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrupos.setOpaque(false);
        btnGrupos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGrupos);

        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/samuel/escuela/icon/users_control_24px.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setFocusable(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setOpaque(false);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuarios);

        jButton1.setText("Asignar Materias");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jScrollPane1.setViewportView(jToolBar1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jdpPrincipal.setBorder(new DesckTopPaneBackGround());
        jdpPrincipal.setAutoscrolls(true);

        jifAlumnos.setClosable(true);
        jifAlumnos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifAlumnos.setIconifiable(true);
        jifAlumnos.setMaximizable(true);
        jifAlumnos.setResizable(true);
        jifAlumnos.setTitle("Alumnos");
        jifAlumnos.setVisible(false);

        jpAlumnos.setLayout(new java.awt.BorderLayout());
        jpAlumnos.add(alumnoMasterDetailForm1, java.awt.BorderLayout.CENTER);

        jScrollPane3.setViewportView(jpAlumnos);

        jifAlumnos.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifAlumnos);
        jifAlumnos.setBounds(170, 60, 450, 320);

        jifMaterias.setClosable(true);
        jifMaterias.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifMaterias.setIconifiable(true);
        jifMaterias.setMaximizable(true);
        jifMaterias.setResizable(true);
        jifMaterias.setTitle("Materias");
        jifMaterias.setVisible(false);

        jScrollPane4.setViewportView(materiaMasterDetailForm1);

        jifMaterias.getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifMaterias);
        jifMaterias.setBounds(190, 90, 420, 320);

        jifProfesores.setClosable(true);
        jifProfesores.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifProfesores.setIconifiable(true);
        jifProfesores.setMaximizable(true);
        jifProfesores.setResizable(true);
        jifProfesores.setTitle("Profesores");
        jifProfesores.setVisible(false);

        jScrollPane5.setViewportView(profesorMasterDetailForm1);

        jifProfesores.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifProfesores);
        jifProfesores.setBounds(280, 100, 441, 330);

        jifGrupos.setClosable(true);
        jifGrupos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifGrupos.setIconifiable(true);
        jifGrupos.setMaximizable(true);
        jifGrupos.setResizable(true);
        jifGrupos.setTitle("Grupos");
        jifGrupos.setVisible(false);

        jScrollPane6.setViewportView(grupoMasterDetailForm1);

        jifGrupos.getContentPane().add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifGrupos);
        jifGrupos.setBounds(210, 80, 430, 280);

        jifUsuarios.setClosable(true);
        jifUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifUsuarios.setIconifiable(true);
        jifUsuarios.setMaximizable(true);
        jifUsuarios.setResizable(true);
        jifUsuarios.setTitle("Usuarios");
        jifUsuarios.setVisible(false);

        jScrollPane7.setViewportView(usuarioMasterDetailForm1);

        jifUsuarios.getContentPane().add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifUsuarios);
        jifUsuarios.setBounds(240, 100, 490, 340);

        jifAsignarMaterias.setClosable(true);
        jifAsignarMaterias.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifAsignarMaterias.setIconifiable(true);
        jifAsignarMaterias.setMaximizable(true);
        jifAsignarMaterias.setResizable(true);
        jifAsignarMaterias.setTitle("Asignar Materia");
        jifAsignarMaterias.setVisible(false);

        jScrollPane8.setViewportView(jpAsignarMaterias);
        jpAsignarMaterias.add(new AsignarMateriaForm(), BorderLayout.CENTER);

        jifAsignarMaterias.getContentPane().add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jdpPrincipal.add(jifAsignarMaterias);
        jifAsignarMaterias.setBounds(150, 40, 590, 390);

        jScrollPane2.setViewportView(jdpPrincipal);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(791, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        showInternalFrame(jifAlumnos);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        showInternalFrame(jifMaterias);
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        showInternalFrame(jifProfesores);
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        showInternalFrame(jifGrupos);
    }//GEN-LAST:event_btnGruposActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        showInternalFrame(jifUsuarios);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showInternalFrame(jifAsignarMaterias);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showInternalFrame(JInternalFrame frame) {
        if (frame != null && (frame.isClosed() || !frame.isVisible())) {
            frame.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.samuel.escuela.form.AlumnoMasterDetailForm alumnoMasterDetailForm1;
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnProfesores;
    private javax.swing.JButton btnUsuarios;
    private com.samuel.escuela.form.GrupoMasterDetailForm grupoMasterDetailForm1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JInternalFrame jifAlumnos;
    private javax.swing.JInternalFrame jifAsignarMaterias;
    private javax.swing.JInternalFrame jifGrupos;
    private javax.swing.JInternalFrame jifMaterias;
    private javax.swing.JInternalFrame jifProfesores;
    private javax.swing.JInternalFrame jifUsuarios;
    private javax.swing.JPanel jpAlumnos;
    private javax.swing.JPanel jpAsignarMaterias;
    private com.samuel.escuela.form.MateriaMasterDetailForm materiaMasterDetailForm1;
    private com.samuel.escuela.form.ProfesorMasterDetailForm profesorMasterDetailForm1;
    private com.samuel.escuela.form.UsuarioMasterDetailForm usuarioMasterDetailForm1;
    // End of variables declaration//GEN-END:variables
}
